# Generated by Django 4.1.5 on 2023-01-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Family', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100, null=True)),
                ('ProfileImage', models.ImageField(upload_to='ProfileImages/')),
            ],
        ),
    ]
