# Generated by Django 4.1.5 on 2023-02-06 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MetaModel', '0002_rename_family_profilemodel_full_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileModel',
        ),
    ]
